### ISSUE TITLE
Hash result is different from scrypt library.

### ISSUE THREAD

**Issue by novemberde** [tracker1/node-js-scrypt#5]
I'm trying to apply this library, but there's an problem.

Compare to other libraries, hash result is totally different.

Here's example code for verification.

```js
const scrypt = require('scrypt');
const jsScrypt = require('js-scrypt');
const scryptsy = require('scryptsy');
const scryptJs = require('scrypt-js');

const salt = 'salt';
const key = 'this is a key';

const N = 16;
const r = 1;
const p = 1;
const dkLen = 64;
const scryptResult = scrypt.hashSync(key, { "N": 16, "r": 1, "p": 1 }, 64, salt);
const jsscryptResult = jsScrypt.hashSync(key, { "N": 16, "r": 1, "p": 1 }, 64, salt);
const scryptsyResult = scryptsy(key, salt, 16,1,1,64);




scryptJs(Buffer.from(key), Buffer.from(salt), N, r, p, dkLen, function (error, progress, key) {
  if (error) {
    console.log("Error: " + error);

  } else if (key) {
    console.log("scryptJsResult: " + Buffer.from(key, 'hex').toString('base64'));
  }
});

console.log('scryptResult: ' + scryptResult.toString('base64'));
console.log('jsscryptResult: ' + jsscryptResult.toString('base64'));
console.log('scryptsyResult: ' + scryptsyResult.toString('base64'));

// Results
scryptJsResult: /TKDucU/c6nSRo6CABG8vwVnK6MeQGs75y1iFlG9Le/sjJ9bQEAEL+Wwvt8zhhZ7Io2Yb8pzQJcnVlV5V6juaQ==
scryptResult: /TKDucU/c6nSRo6CABG8vwVnK6MeQGs75y1iFlG9Le/sjJ9bQEAEL+Wwvt8zhhZ7Io2Yb8pzQJcnVlV5V6juaQ==
jsscryptResult: 5zaU49mSsd8JzgoUKimk+ci9QjyPFq8pLz0AN5O3PVqQtWgQWZHnHzCW7Fk7Y0NeP3gUW98PKaCcPC65udtFbw==
scryptsyResult: /TKDucU/c6nSRo6CABG8vwVnK6MeQGs75y1iFlG9Le/sjJ9bQEAEL+Wwvt8zhhZ7Io2Yb8pzQJcnVlV5V6juaQ==
```

Only this library returns a different result.

Are there any option to fix this situation?

I'm looking forward to your answer.

Thank you.

**Comment by tracker1** [comment]
I didn't write the underlying js-script, it was copied from an asm compiled version about 6 years ago...  so I cannot really comment on that aspect, all I did at that time was write wrappers so that I could at least run a few instances in the background in node via a pool of connected workers.

I should probably just deprecate the package in npm and point to one of the other versions...  IIRC, when I wrote it, my results were matching a .Net implementation...

Do you have one you would recommend over the others?

**Comment by tracker1** [comment]
Aside, I don't know that I should fix it.. if anyone is using this library currently, I could maybe bump the full version with a NOTE and make this just a wrapper against one of the other libraries you're referencing.

**Comment by tracker1** [comment]
Looks like the upstream version I used in my copy had an incompatibility with the current one...

https://github.com/tonyg/js-scrypt/commits/master/browser/scrypt.js
https://github.com/tonyg/js-scrypt/

Again, more than open to suggestions on a library to wrap around the same interface... though, should also consider the newer worker in node 11.7 as well as a Promise based interface.

**Comment by novemberde** [comment]
@tracker1 Thank you for your answer.

I found the difference among that libraries. Each library has different function parameter.
Actually, I'd aliased js-scrypt instead of scrypt for making a bundle using webpack, so I found it returns different hash result.

Now, I include 'scrypt' on webpack bundling, it works well!
All is fine.

Thank you again :)
